version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./ops/docker/Dockerfile
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    container_name: app
    env_file:
      - .env
    volumes:
      - .:/var/www/app
    networks:
      - app
    depends_on:
      - database

  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www/app
      - ./ops/nginx/nginx-conf.d:/etc/nginx/conf.d
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app
    depends_on:
      - app

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    restart: unless-stopped
    volumes:
      - ./ops/posgre/init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./ops/postgre/data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - app

volumes:
  db-data:

networks:
  app:
    driver: bridge
